export default function ProposalPage() {
  return (
    <main className="min-h-screen bg-gray-100 py-10">
      <div className="max-w-4xl mx-auto bg-white p-10 rounded-xl shadow-lg">

        <div className="border-b pb-6 mb-6">
          <h1 className="text-4xl font-bold">
            AI Project Proposal
          </h1>

          <p className="text-gray-500 mt-2">
            Generated by AI Lead Qualification Assistant
          </p>
        </div>

        <div className="space-y-4">

          <h2 className="text-2xl font-semibold">
            Client Information
          </h2>

          <p><strong>Name:</strong> Deepak Kumar</p>
          <p><strong>Email:</strong> deepak@gmail.com</p>

          <h2 className="text-2xl font-semibold mt-8">
            Project Overview
          </h2>

          <p>
            Development of a modern Ecommerce Website
            with payment integration, admin panel and
            secure authentication system.
          </p>

          <h2 className="text-2xl font-semibold mt-8">
            Scope of Work
          </h2>

          <ul className="list-disc ml-8">
            <li>Responsive UI Design</li>
            <li>Admin Dashboard</li>
            <li>Payment Gateway</li>
            <li>User Authentication</li>
            <li>Database Integration</li>
          </ul>

          <h2 className="text-2xl font-semibold mt-8">
            Timeline
          </h2>

          <p>1 Month</p>

          <h2 className="text-2xl font-semibold mt-8">
            Budget
          </h2>

          <p>₹50,000</p>

          <h2 className="text-2xl font-semibold mt-8">
            Lead Analysis
          </h2>

          <p><strong>Lead Score:</strong> 95/100</p>

          <p>
            <strong>Lead Quality:</strong>
            {" "}High Quality Lead
          </p>

        </div>
      </div>
    </main>
  );
}