"use client";
import { jsPDF } from "jspdf";
export default function ProposalPage() {
  const downloadPDF = () => {
  const doc = new jsPDF();

  doc.setFontSize(20);
  doc.text("AI Project Proposal", 20, 20);

  doc.setFontSize(12);
  doc.text("Client Name: Deepak Kumar", 20, 40);
  doc.text("Email: deepak@gmail.com", 20, 50);

  doc.text("Project: Ecommerce Website", 20, 70);
  doc.text("Budget: ₹50,000", 20, 80);
  doc.text("Timeline: 1 Month", 20, 90);

  doc.text("Features:", 20, 110);
  doc.text("- Payment Gateway", 30, 120);
  doc.text("- Admin Panel", 30, 130);
  doc.text("- Login System", 30, 140);

  doc.text("Lead Score: 95/100", 20, 170);
  doc.text("Lead Quality: High Quality Lead", 20, 180);

  doc.save("proposal.pdf");
};
  return (
  <main className="min-h-screen bg-gray-100 py-10">
    <div className="max-w-4xl mx-auto">

      <button
        onClick={downloadPDF}
        className="mb-6 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg text-sm"
      >
        Download Proposal PDF
      </button>

      <div className="bg-white p-10 rounded-xl shadow-lg">

        <div className="border-b pb-6 mb-6">
          <h1 className="text-4xl font-bold">
            AI Project Proposal
          </h1>

          <p className="text-gray-500 mt-2">
            Generated by AI Lead Qualification Assistant
          </p>
        </div>

        <div className="space-y-4">

          <h2 className="text-2xl font-semibold">
            Client Information
          </h2>

          <p><strong>Name:</strong> Deepak Kumar</p>
          <p><strong>Email:</strong> deepak@gmail.com</p>

          <h2 className="text-2xl font-semibold mt-8">
            Project Overview
          </h2>

          <p>
            Development of a modern Ecommerce Website
            with payment integration, admin panel and
            secure authentication system.
          </p>

          <h2 className="text-2xl font-semibold mt-8">
            Scope of Work
          </h2>

          <ul className="list-disc ml-8">
            <li>Responsive UI Design</li>
            <li>Admin Dashboard</li>
            <li>Payment Gateway</li>
            <li>User Authentication</li>
            <li>Database Integration</li>
          </ul>

          <h2 className="text-2xl font-semibold mt-8">
            Timeline
          </h2>

          <p>1 Month</p>

          <h2 className="text-2xl font-semibold mt-8">
            Budget
          </h2>

          <p>₹50,000</p>

          <h2 className="text-2xl font-semibold mt-8">
            Lead Analysis
          </h2>

          <p><strong>Lead Score:</strong> 95/100</p>

          <p>
            <strong>Lead Quality:</strong> High Quality Lead
          </p>

        </div>

      </div>
    </div>
  </main>
);
}